# Generated by Django 5.0.2 on 2024-03-29 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('antiCorruptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anticorruption',
            name='title_kk',
            field=models.CharField(null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='anticorruption',
            name='title_ru',
            field=models.CharField(null=True, verbose_name='Название'),
        ),
    ]
