# Generated by Django 5.0.2 on 2024-03-29 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history_legends', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='info_kk',
            field=models.TextField(null=True, verbose_name='Information'),
        ),
        migrations.AddField(
            model_name='history',
            name='info_ru',
            field=models.TextField(null=True, verbose_name='Information'),
        ),
        migrations.AddField(
            model_name='history',
            name='title_kk',
            field=models.CharField(null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='history',
            name='title_ru',
            field=models.CharField(null=True, verbose_name='Title'),
        ),
    ]
