# Generated by Django 5.0.2 on 2024-03-29 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history_legends', '0002_history_info_kk_history_info_ru_history_title_kk_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='info_kk',
            new_name='info_kz',
        ),
        migrations.RenameField(
            model_name='history',
            old_name='title_kk',
            new_name='title_kz',
        ),
    ]
