# Generated by Django 5.0.2 on 2024-03-29 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('antiCorruptions', '0002_anticorruption_title_kk_anticorruption_title_ru'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anticorruption',
            old_name='title_kk',
            new_name='title_kz',
        ),
    ]
