# Generated by Django 5.0.2 on 2024-03-26 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='postattachment',
            name='type',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
