# Generated by Django 5.0.2 on 2024-03-29 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_rename_content_kk_post_content_kz_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content_kz',
            new_name='content_kk',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title_kz',
            new_name='title_kk',
        ),
    ]
