# Generated by Django 5.0.2 on 2024-03-29 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='index_page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bannerContent', models.TextField(verbose_name='Текста на баннере')),
                ('bannerContent_ru', models.TextField(null=True, verbose_name='Текста на баннере')),
                ('bannerContent_kk', models.TextField(null=True, verbose_name='Текста на баннере')),
                ('ceo_appeal', models.TextField(verbose_name='Обращение руководителя')),
                ('ceo_appeal_ru', models.TextField(null=True, verbose_name='Обращение руководителя')),
                ('ceo_appeal_kk', models.TextField(null=True, verbose_name='Обращение руководителя')),
            ],
        ),
    ]
