# Generated by Django 5.0.2 on 2024-03-29 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_post_content_kk_post_content_ru_post_title_kk_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='content_kk',
            new_name='content_kz',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title_kk',
            new_name='title_kz',
        ),
    ]
