# Generated by Django 5.0.2 on 2024-03-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('About', models.TextField(verbose_name='Описание')),
                ('LDO', models.TextField(verbose_name='Лечебно-Диагностическое отделение')),
                ('file', models.FileField(upload_to='', verbose_name='Файл с описанием')),
            ],
        ),
    ]
