# Generated by Django 5.0.2 on 2024-03-29 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutPage', '0004_rename_about_kz_aboutinfo_about_kk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutinfo',
            name='file',
            field=models.FileField(upload_to='docs/', verbose_name='Файл с описанием'),
        ),
    ]
