# Generated by Django 5.0.2 on 2024-03-22 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewSovet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewsovet',
            name='file',
            field=models.FileField(upload_to='docs/', verbose_name='Документ'),
        ),
    ]
