# Generated by Django 5.0.2 on 2024-03-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewSovet', '0002_alter_viewsovet_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewsovet',
            name='title_kk',
            field=models.CharField(null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='viewsovet',
            name='title_ru',
            field=models.CharField(null=True, verbose_name='Название'),
        ),
    ]
