# Generated by Django 5.0.2 on 2024-03-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutPage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutinfo',
            name='About_kk',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='aboutinfo',
            name='About_ru',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='aboutinfo',
            name='LDO_kk',
            field=models.TextField(null=True, verbose_name='Лечебно-Диагностическое отделение'),
        ),
        migrations.AddField(
            model_name='aboutinfo',
            name='LDO_ru',
            field=models.TextField(null=True, verbose_name='Лечебно-Диагностическое отделение'),
        ),
    ]
