# Generated by Django 5.0.2 on 2024-03-29 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProvActs', '0003_provacts_description_kk_provacts_description_ru'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provacts',
            old_name='description_kk',
            new_name='description_kz',
        ),
    ]
