# Generated by Django 5.0.2 on 2024-03-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='title_kk',
            field=models.CharField(null=True, verbose_name='Заголовок объявления'),
        ),
        migrations.AddField(
            model_name='ads',
            name='title_ru',
            field=models.CharField(null=True, verbose_name='Заголовок объявления'),
        ),
        migrations.AddField(
            model_name='files',
            name='name_kk',
            field=models.CharField(null=True, verbose_name='Название файла'),
        ),
        migrations.AddField(
            model_name='files',
            name='name_ru',
            field=models.CharField(null=True, verbose_name='Название файла'),
        ),
    ]
