# Generated by Django 5.0.2 on 2024-03-22 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ceoInfo', '0003_education_ceo_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='ceo_id',
            new_name='ceo',
        ),
    ]
