# Generated by Django 5.0.2 on 2024-03-29 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info_page', '0007_rename_info_kk_pacientinfo_info_kz_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pacientinfo',
            old_name='info_kz',
            new_name='info_kk',
        ),
        migrations.RenameField(
            model_name='pacientinfo',
            old_name='title_kz',
            new_name='title_kk',
        ),
    ]
