# Generated by Django 5.0.2 on 2024-03-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkersInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='ФИО')),
                ('post', models.TextField(verbose_name='Должность')),
                ('work_exp', models.CharField(verbose_name='Стаж')),
                ('sertificates', models.TextField(verbose_name='Сертификат специалиста')),
            ],
        ),
    ]
