# Generated by Django 5.0.2 on 2024-03-23 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProvActs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provacts',
            name='title',
        ),
    ]
