# Generated by Django 5.0.2 on 2024-03-29 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProvActs', '0004_rename_description_kk_provacts_description_kz'),
    ]

    operations = [
        migrations.RenameField(
            model_name='provacts',
            old_name='description_kz',
            new_name='description_kk',
        ),
    ]
