# Generated by Django 5.0.2 on 2024-03-29 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info_page', '0005_delete_contacts_delete_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientinfo',
            name='info_kk',
            field=models.TextField(null=True, verbose_name='Information'),
        ),
        migrations.AddField(
            model_name='pacientinfo',
            name='info_ru',
            field=models.TextField(null=True, verbose_name='Information'),
        ),
        migrations.AddField(
            model_name='pacientinfo',
            name='title_kk',
            field=models.CharField(null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='pacientinfo',
            name='title_ru',
            field=models.CharField(null=True, verbose_name='Title'),
        ),
    ]
