# Generated by Django 5.0.2 on 2024-03-29 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='info_kk',
            field=models.TextField(null=True, verbose_name='Information'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='info_ru',
            field=models.TextField(null=True, verbose_name='Information'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='title_kk',
            field=models.CharField(null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='contacts',
            name='title_ru',
            field=models.CharField(null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='managers',
            name='name_kk',
            field=models.CharField(max_length=128, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='managers',
            name='name_ru',
            field=models.CharField(max_length=128, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='managers',
            name='post_kk',
            field=models.TextField(null=True, verbose_name='Post'),
        ),
        migrations.AddField(
            model_name='managers',
            name='post_ru',
            field=models.TextField(null=True, verbose_name='Post'),
        ),
        migrations.AddField(
            model_name='managers',
            name='reception_kk',
            field=models.TextField(default='none', null=True, verbose_name='Day and time of reception'),
        ),
        migrations.AddField(
            model_name='managers',
            name='reception_ru',
            field=models.TextField(default='none', null=True, verbose_name='Day and time of reception'),
        ),
    ]
