# Generated by Django 5.0.2 on 2024-03-21 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(verbose_name='Title')),
                ('info', models.TextField(verbose_name='Information')),
            ],
        ),
        migrations.CreateModel(
            name='Managers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('post', models.TextField(verbose_name='Post')),
                ('phone', models.CharField(verbose_name='Phone number')),
                ('email', models.CharField(verbose_name='E-mail')),
                ('reception', models.TextField(default='none', verbose_name='Day and time of reception')),
                ('show', models.BooleanField(verbose_name='Show this person in second table?')),
            ],
        ),
    ]
