# Generated by Django 5.0.2 on 2024-03-22 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compAddress', models.TextField(verbose_name='Адрес конкурса')),
                ('enterpriseAddress', models.TextField(verbose_name='Адрес предприятия')),
                ('description', models.TextField(verbose_name='Краткое описание')),
                ('addmisions', models.TextField(verbose_name='Условия допуска к участию')),
                ('documents', models.TextField(verbose_name='Список предоставляемсях документов')),
                ('additionally', models.TextField(verbose_name='Дополнительная информация')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacancy', models.TextField(verbose_name='Вакансия')),
                ('requirement', models.TextField(verbose_name='Требования')),
            ],
        ),
    ]
