# Generated by Django 5.0.2 on 2024-03-29 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitioninfo',
            name='additionally_kk',
            field=models.TextField(null=True, verbose_name='Дополнительная информация'),
        ),
        migrations.AddField(
            model_name='competitioninfo',
            name='additionally_ru',
            field=models.TextField(null=True, verbose_name='Дополнительная информация'),
        ),
        migrations.AddField(
            model_name='competitioninfo',
            name='addmisions_kk',
            field=models.TextField(null=True, verbose_name='Условия допуска к участию'),
        ),
        migrations.AddField(
            model_name='competitioninfo',
            name='addmisions_ru',
            field=models.TextField(null=True, verbose_name='Условия допуска к участию'),
        ),
        migrations.AddField(
            model_name='competitioninfo',
            name='compAddress_kk',
            field=models.TextField(null=True, verbose_name='Адрес конкурса'),
        ),
        migrations.AddField(
            model_name='competitioninfo',
            name='compAddress_ru',
            field=models.TextField(null=True, verbose_name='Адрес конкурса'),
        ),
        migrations.AddField(
            model_name='competitioninfo',
            name='description_kk',
            field=models.TextField(null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='competitioninfo',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Краткое описание'),
        ),
        migrations.AddField(
            model_name='competitioninfo',
            name='documents_kk',
            field=models.TextField(null=True, verbose_name='Список предоставляемсях документов'),
        ),
        migrations.AddField(
            model_name='competitioninfo',
            name='documents_ru',
            field=models.TextField(null=True, verbose_name='Список предоставляемсях документов'),
        ),
        migrations.AddField(
            model_name='competitioninfo',
            name='enterpriseAddress_kk',
            field=models.TextField(null=True, verbose_name='Адрес предприятия'),
        ),
        migrations.AddField(
            model_name='competitioninfo',
            name='enterpriseAddress_ru',
            field=models.TextField(null=True, verbose_name='Адрес предприятия'),
        ),
        migrations.AddField(
            model_name='vacancies',
            name='requirement_kk',
            field=models.TextField(null=True, verbose_name='Требования'),
        ),
        migrations.AddField(
            model_name='vacancies',
            name='requirement_ru',
            field=models.TextField(null=True, verbose_name='Требования'),
        ),
        migrations.AddField(
            model_name='vacancies',
            name='vacancy_kk',
            field=models.TextField(null=True, verbose_name='Вакансия'),
        ),
        migrations.AddField(
            model_name='vacancies',
            name='vacancy_ru',
            field=models.TextField(null=True, verbose_name='Вакансия'),
        ),
    ]
