# Generated by Django 5.0.2 on 2024-03-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CeoDatas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name='Имя руководителя')),
                ('dateOfBirth', models.CharField(verbose_name='Дата рождания')),
                ('education', models.TextField(verbose_name='Образование')),
                ('scientific', models.TextField(verbose_name='Научная степень')),
                ('work_ex', models.TextField(verbose_name='Опыт работы')),
                ('additionally', models.TextField(verbose_name='Дополнительно')),
                ('awards', models.TextField(verbose_name='Награды')),
                ('sertificates', models.TextField(verbose_name='Сертификаты')),
                ('publications', models.TextField(verbose_name='Публикации')),
            ],
        ),
    ]
