# Generated by Django 5.0.2 on 2024-03-22 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceoInfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.TextField(verbose_name='Учебное учреждание')),
                ('info', models.TextField(verbose_name='Информация об образование в данном учреждении')),
            ],
        ),
        migrations.RemoveField(
            model_name='ceodatas',
            name='education',
        ),
    ]
