# Generated by Django 5.0.2 on 2024-03-22 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceoInfo', '0002_education_remove_ceodatas_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='ceo_id',
            field=models.ForeignKey(default=-2005, on_delete=django.db.models.deletion.CASCADE, to='ceoInfo.ceodatas'),
            preserve_default=False,
        ),
    ]
