# Generated by Django 5.0.2 on 2024-03-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceoInfo', '0004_rename_ceo_id_education_ceo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ceodatas',
            name='photo',
            field=models.FileField(default=-2003, upload_to='', verbose_name='Фото руководителя'),
            preserve_default=False,
        ),
    ]
