# Generated by Django 5.0.2 on 2024-03-29 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ceoInfo', '0006_alter_ceodatas_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ceodatas',
            name='additionally_kk',
            field=models.TextField(null=True, verbose_name='Дополнительно'),
        ),
        migrations.AddField(
            model_name='ceodatas',
            name='additionally_ru',
            field=models.TextField(null=True, verbose_name='Дополнительно'),
        ),
        migrations.AddField(
            model_name='ceodatas',
            name='awards_kk',
            field=models.TextField(null=True, verbose_name='Награды'),
        ),
        migrations.AddField(
            model_name='ceodatas',
            name='awards_ru',
            field=models.TextField(null=True, verbose_name='Награды'),
        ),
        migrations.AddField(
            model_name='ceodatas',
            name='dateOfBirth_kk',
            field=models.CharField(null=True, verbose_name='Дата рождания'),
        ),
        migrations.AddField(
            model_name='ceodatas',
            name='dateOfBirth_ru',
            field=models.CharField(null=True, verbose_name='Дата рождания'),
        ),
        migrations.AddField(
            model_name='ceodatas',
            name='name_kk',
            field=models.CharField(null=True, verbose_name='Имя руководителя'),
        ),
        migrations.AddField(
            model_name='ceodatas',
            name='name_ru',
            field=models.CharField(null=True, verbose_name='Имя руководителя'),
        ),
        migrations.AddField(
            model_name='ceodatas',
            name='publications_kk',
            field=models.TextField(null=True, verbose_name='Публикации'),
        ),
        migrations.AddField(
            model_name='ceodatas',
            name='publications_ru',
            field=models.TextField(null=True, verbose_name='Публикации'),
        ),
        migrations.AddField(
            model_name='ceodatas',
            name='scientific_kk',
            field=models.TextField(null=True, verbose_name='Научная степень'),
        ),
        migrations.AddField(
            model_name='ceodatas',
            name='scientific_ru',
            field=models.TextField(null=True, verbose_name='Научная степень'),
        ),
        migrations.AddField(
            model_name='ceodatas',
            name='sertificates_kk',
            field=models.TextField(null=True, verbose_name='Сертификаты'),
        ),
        migrations.AddField(
            model_name='ceodatas',
            name='sertificates_ru',
            field=models.TextField(null=True, verbose_name='Сертификаты'),
        ),
        migrations.AddField(
            model_name='ceodatas',
            name='work_ex_kk',
            field=models.TextField(null=True, verbose_name='Опыт работы'),
        ),
        migrations.AddField(
            model_name='ceodatas',
            name='work_ex_ru',
            field=models.TextField(null=True, verbose_name='Опыт работы'),
        ),
        migrations.AddField(
            model_name='education',
            name='info_kk',
            field=models.TextField(null=True, verbose_name='Информация об образование в данном учреждении'),
        ),
        migrations.AddField(
            model_name='education',
            name='info_ru',
            field=models.TextField(null=True, verbose_name='Информация об образование в данном учреждении'),
        ),
        migrations.AddField(
            model_name='education',
            name='university_kk',
            field=models.TextField(null=True, verbose_name='Учебное учреждание'),
        ),
        migrations.AddField(
            model_name='education',
            name='university_ru',
            field=models.TextField(null=True, verbose_name='Учебное учреждание'),
        ),
    ]
