# Generated by Django 5.0.2 on 2024-03-29 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ceoInfo', '0007_ceodatas_additionally_kk_ceodatas_additionally_ru_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ceodatas',
            old_name='additionally_kk',
            new_name='additionally_kz',
        ),
        migrations.RenameField(
            model_name='ceodatas',
            old_name='awards_kk',
            new_name='awards_kz',
        ),
        migrations.RenameField(
            model_name='ceodatas',
            old_name='dateOfBirth_kk',
            new_name='dateOfBirth_kz',
        ),
        migrations.RenameField(
            model_name='ceodatas',
            old_name='name_kk',
            new_name='name_kz',
        ),
        migrations.RenameField(
            model_name='ceodatas',
            old_name='publications_kk',
            new_name='publications_kz',
        ),
        migrations.RenameField(
            model_name='ceodatas',
            old_name='scientific_kk',
            new_name='scientific_kz',
        ),
        migrations.RenameField(
            model_name='ceodatas',
            old_name='sertificates_kk',
            new_name='sertificates_kz',
        ),
        migrations.RenameField(
            model_name='ceodatas',
            old_name='work_ex_kk',
            new_name='work_ex_kz',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='info_kk',
            new_name='info_kz',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='university_kk',
            new_name='university_kz',
        ),
    ]
