# Generated by Django 5.0.2 on 2024-03-29 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workersInfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workersinfo',
            name='post_kk',
            field=models.TextField(null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='workersinfo',
            name='post_ru',
            field=models.TextField(null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='workersinfo',
            name='sertificates_kk',
            field=models.TextField(null=True, verbose_name='Сертификат специалиста'),
        ),
        migrations.AddField(
            model_name='workersinfo',
            name='sertificates_ru',
            field=models.TextField(null=True, verbose_name='Сертификат специалиста'),
        ),
    ]
