# Generated by Django 5.0.2 on 2024-03-29 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workersInfo', '0002_workersinfo_post_kk_workersinfo_post_ru_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workersinfo',
            old_name='post_kk',
            new_name='post_kz',
        ),
        migrations.RenameField(
            model_name='workersinfo',
            old_name='sertificates_kk',
            new_name='sertificates_kz',
        ),
    ]
